language: php

addons:
  chrome: stable

php:
  - 7.0

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - composer install --prefer-dist
  - chmod 777 -R storage

script:
  - sh travis-env.sh
  - vendor/bin/behat
