language: php

addons:
  chrome: stable

php:
  - 7.0

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - composer install --prefer-dist
  - chmod 777 -R storage
  - google-chrome-stable --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 &
  - php artisan serve &
  
script:
  - vendor/bin/behat
