language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - composer install --prefer-dist
  - chmod 777 -R storage
  - selenium-standalone start
  - php artisan serve

script:
  - vendor/bin/behat
